os:
  - linux
  - osx

language: python
    - "2.7"

before_install:
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo apt-get update -qq; sudo apt-get install -y gfortran xvfb; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then wget https://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh; fi

  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew update ; fi 
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then wget https://repo.continuum.io/miniconda/Miniconda-latest-MacOSX-x86_64.sh -O miniconda.sh; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then wget https://github.com/UV-CDAT/uvcdat/releases/download/v2.4.1/gfortran-4.9.2-Mac.tar.gz -O ~/gfortran-4.9.2-Mac.tar.gz ; pushd / ; sudo tar xzvf ~/gfortran-4.9.2-Mac.tar.gz ; popd ; fi
  - export PATH="$HOME/miniconda/bin:$PATH"
  - bash miniconda.sh -b -p $HOME/miniconda
  - conda config --set always_yes yes --set changeps1 no
  - conda update -y -q conda
  - conda install openssl=1.0.2d
  - conda install cdms2 -c uvcdat

install:
    - cd ..
    - export PREFIX=$HOME/_build
    - mkdir ${PREFIX}
    - cd ${PREFIX}
    - wget http://www.mirrorservice.org/sites/ftp.ossp.org/pkg/lib/uuid/uuid-1.6.2.tar.gz -O ~/uuid-1.6.2.tar.gz 
    - tar xzf ~/uuid-1.6.2.tar.gz
    - pushd uuid-1.6.2 && ./configure --prefix=$PREFIX && make && make install && popd 
    - wget ftp://ftp.unidata.ucar.edu/pub/udunits/udunits-2.2.20.tar.gz -O ~/udunits-2.2.20.tar.gz 
    - tar xzf ~/udunits-2.2.20.tar.gz
    - pushd udunits-2.2.20 && ./configure --prefix=$PREFIX && make && make install && popd
    - wget http://www.hdfgroup.org/ftp/HDF5/current/src/hdf5-1.8.17.tar -O ~/hdf5-1.8.17.tar
    - tar xvf ~/hdf5-1.8.17.tar
    - pushd hdf5-1.8.17 &&  ./configure --prefix=$PREFIX && make && make install && popd
    - export CFLAGS="-I${PREFIX}/include"
    - export LDFLAGS="-L${PREFIX}/lib"
    - wget ftp://ftp.unidata.ucar.edu/pub/netcdf/netcdf-4.4.0.tar.gz -O ~/netcdf-4.4.0.tar.gz 
    - tar xzf ~/netcdf-4.4.0.tar.gz
    - pushd netcdf-4.4.0 && ./configure --prefix=$PREFIX --enable-netcdf4 && make && make install && popd
    - cd ${PREFIX}
    - git clone https://github.com/PCMDI/cmor.git
    - pushd  cmor &&./configure --prefix=$PREFIX --with-python --with-uuid --with-udunits --with-netcdf=$PREFIX/  && make && make install && make python && popd
script:
    - cd ${PREFIX}
    - make test

